indent_style = "Block"
reorder_imports = true
chain_width = 120
max_width = 120

force_multiline_blocks = true
match_block_trailing_comma = true
imports_granularity = "Crate"
normalize_comments = true
group_imports = "StdExternalCrate"
